### ISSUE TITLE
Release not pushed to bonsai

### ISSUE THREAD

**Issue by VeselaHouba** [sensu-plugins/sensu-plugins-filesystem-checks#57]
There are no new releases being bushed to bonsai since 2.0.0
https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-filesystem-checks/
Maybe some issue in travis CI?

**Comment by VeselaHouba** [comment]
bump
![image](https://user-images.githubusercontent.com/6410423/120226427-79fca880-c247-11eb-9733-f608c0252aaa.png)
:(

**Comment by jspaleta** [comment]
Releases should be on bonsai now.

**Comment by VeselaHouba** [comment]
yeeeey!
